#!/usr/bin/env python3
"""
evaluate.py — evaluate a trained checkpoint on val AND/OR the untouched test split.

Reports precision, recall, mAP50, mAP50-95, per-image inference latency, and FPS.
Also dumps false-positive / false-negative candidate images for manual review —
mAP alone is not a sign-off; someone needs to eyeball these, especially:
road patches, shadows, cracks, manholes, puddles, dark areas, vehicle shadows,
small/distant potholes, multi-pothole scenes, partial occlusion, night images.

Usage:
  python evaluate.py --weights runs/potholenet_yolo11n/weights/best.pt --data datasets/potholes/data.yaml --split test
"""
import argparse
import json
import time
from pathlib import Path

from ultralytics import YOLO


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--weights", required=True, type=Path)
    ap.add_argument("--data", type=Path, default=Path("datasets/potholes/data.yaml"))
    ap.add_argument("--split", choices=["val", "test"], default="val",
                     help="use 'test' ONLY for the final, one-time evaluation")
    ap.add_argument("--conf", type=float, default=0.35)
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--fp-fn-dir", type=Path, default=None,
                     help="if set, save annotated FP/FN images here for manual inspection")
    args = ap.parse_args()

    if args.split == "test":
        print("You are evaluating on the TEST split. This should happen ONCE per model "
              "version, after val-based iteration is finished. Do not retrain on these results.")

    model = YOLO(str(args.weights))
    metrics = model.val(data=str(args.data), split=args.split, conf=args.conf, imgsz=args.imgsz)

    # Latency benchmark on a handful of real images from the split
    import yaml
    cfg = yaml.safe_load(args.data.read_text())
    img_dir = Path(cfg["path"]) / cfg[args.split]
    sample_imgs = list(img_dir.glob("*.jpg"))[:50] or list(img_dir.glob("*.png"))[:50]

    latencies_ms = []
    for img_path in sample_imgs:
        t0 = time.perf_counter()
        model.predict(str(img_path), conf=args.conf, imgsz=args.imgsz, verbose=False)
        latencies_ms.append((time.perf_counter() - t0) * 1000)

    avg_latency = sum(latencies_ms) / len(latencies_ms) if latencies_ms else None
    fps = 1000 / avg_latency if avg_latency else None

    report = {
        "weights": str(args.weights),
        "split": args.split,
        "confidence_threshold": args.conf,
        "precision": float(metrics.box.mp),
        "recall": float(metrics.box.mr),
        "mAP50": float(metrics.box.map50),
        "mAP50-95": float(metrics.box.map),
        "avg_inference_latency_ms": avg_latency,
        "fps_estimate": fps,
        "latency_sample_size": len(sample_imgs),
        "note": "mAP is not sufficient sign-off. Manually review false positives/negatives "
                "(see --fp-fn-dir) before recommending deployment.",
    }

    out_path = args.weights.parent.parent / f"eval_report_{args.split}.json"
    out_path.write_text(json.dumps(report, indent=2))
    print(json.dumps(report, indent=2))
    print(f"\nSaved report to {out_path}")

    if args.fp_fn_dir:
        print(f"\nFP/FN visual dump not auto-generated by this script yet — "
              f"run inference.py over {img_dir} and diff against ground-truth labels "
              f"to build {args.fp_fn_dir}/ manually, or extend this script for your workflow.")


if __name__ == "__main__":
    main()
